// <auto-generated />
using System;
using Demo.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503065723_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Demo.Shared.Domain.Badge", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("id")
                        .HasName("pk_badges");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("ix_badges_name");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("Demo.Shared.Domain.Comment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("postId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<int>("score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<long>("userId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("id")
                        .HasName("pk_comments");

                    b.HasIndex("postId")
                        .HasDatabaseName("ix_comments_post_id");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Demo.Shared.Domain.Post", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("acceptedAnswerId")
                        .HasColumnType("bigint")
                        .HasColumnName("accepted_answer_id");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<int>("commentCount")
                        .HasColumnType("int")
                        .HasColumnName("comment_count");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deleted");

                    b.Property<long?>("parentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("postType")
                        .HasColumnType("int")
                        .HasColumnName("post_type");

                    b.Property<int?>("questionType")
                        .HasColumnType("int")
                        .HasColumnName("question_type");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<long>("userId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("viewCount")
                        .HasColumnType("int")
                        .HasColumnName("view_count");

                    b.Property<int>("voteCount")
                        .HasColumnType("int")
                        .HasColumnName("vote_count");

                    b.HasKey("id")
                        .HasName("pk_posts");

                    b.HasIndex("acceptedAnswerId")
                        .IsUnique()
                        .HasDatabaseName("ix_posts_accepted_answer_id");

                    b.HasIndex("parentId")
                        .HasDatabaseName("ix_posts_parent_id");

                    b.HasIndex("slug")
                        .IsUnique()
                        .HasDatabaseName("ix_posts_slug");

                    b.HasIndex("userId")
                        .HasDatabaseName("ix_posts_user_id");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Demo.Shared.Domain.PostApproval", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("adminId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("postId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("processedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("rejectionReason")
                        .HasColumnType("longtext")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("id")
                        .HasName("pk_post_approvals");

                    b.HasIndex("adminId")
                        .HasDatabaseName("ix_post_approvals_admin_id");

                    b.HasIndex("postId")
                        .HasDatabaseName("ix_post_approvals_post_id");

                    b.ToTable("post_approvals", (string)null);
                });

            modelBuilder.Entity("Demo.Shared.Domain.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("id")
                        .HasName("pk_roles");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            code = "User",
                            name = "User"
                        },
                        new
                        {
                            id = 2,
                            code = "Admin",
                            name = "Admin"
                        });
                });

            modelBuilder.Entity("Demo.Shared.Domain.Tag", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<int>("usageCount")
                        .HasColumnType("int")
                        .HasColumnName("usage_count");

                    b.HasKey("id")
                        .HasName("pk_tags");

                    b.HasIndex("name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Demo.Shared.Domain.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("aboutMe")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("about_me");

                    b.Property<string>("avatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deleted");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("reputation")
                        .HasColumnType("int")
                        .HasColumnName("reputation");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("websiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("website_url");

                    b.HasKey("id")
                        .HasName("pk_users");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("userName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1L,
                            createdAt = new DateTime(2026, 5, 3, 13, 57, 22, 514, DateTimeKind.Local).AddTicks(345),
                            deleted = false,
                            displayName = "Admin",
                            email = "admin@gmail.com",
                            passwordHash = "$2a$11$DQX8A86G9nRrv2LicA2mQO1p0EEzBZCsKFpXgDHOlyVLO8XRiyIL6",
                            reputation = 0,
                            userName = "admin"
                        });
                });

            modelBuilder.Entity("Demo.Shared.Domain.Vote", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("createdAt"));

                    b.Property<long>("postId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<long>("userId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("voteType")
                        .HasColumnType("int")
                        .HasColumnName("vote_type");

                    b.HasKey("id")
                        .HasName("pk_votes");

                    b.HasIndex("postId")
                        .HasDatabaseName("ix_votes_post_id");

                    b.HasIndex("userId", "postId")
                        .IsUnique()
                        .HasDatabaseName("ix_votes_user_id_post_id");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("post_tags", b =>
                {
                    b.Property<long>("post_id")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<long>("tag_id")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("post_id", "tag_id")
                        .HasName("pk_post_tags");

                    b.HasIndex("tag_id")
                        .HasDatabaseName("ix_post_tags_tag_id");

                    b.ToTable("post_tags", (string)null);
                });

            modelBuilder.Entity("user_badges", b =>
                {
                    b.Property<long>("badge_id")
                        .HasColumnType("bigint")
                        .HasColumnName("badge_id");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("badge_id", "user_id")
                        .HasName("pk_user_badges");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_user_badges_user_id");

                    b.ToTable("user_badges", (string)null);
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<int>("role_id")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("role_id", "user_id")
                        .HasName("pk_user_roles");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            role_id = 2,
                            user_id = 1L
                        });
                });

            modelBuilder.Entity("Demo.Shared.Domain.Comment", b =>
                {
                    b.HasOne("Demo.Shared.Domain.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_posts_post_id");

                    b.HasOne("Demo.Shared.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Demo.Shared.Domain.Post", b =>
                {
                    b.HasOne("Demo.Shared.Domain.Post", "AcceptedAnswer")
                        .WithOne()
                        .HasForeignKey("Demo.Shared.Domain.Post", "acceptedAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_posts_posts_accepted_answer_id");

                    b.HasOne("Demo.Shared.Domain.Post", "ParentPost")
                        .WithMany("ChildAnswers")
                        .HasForeignKey("parentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_posts_posts_parent_id");

                    b.HasOne("Demo.Shared.Domain.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_users_user_id");

                    b.Navigation("AcceptedAnswer");

                    b.Navigation("ParentPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Demo.Shared.Domain.PostApproval", b =>
                {
                    b.HasOne("Demo.Shared.Domain.User", "User")
                        .WithMany("PostApprovals")
                        .HasForeignKey("adminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_post_approvals_users_admin_id");

                    b.HasOne("Demo.Shared.Domain.Post", "Post")
                        .WithMany("Approvals")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_approvals_posts_post_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Demo.Shared.Domain.Vote", b =>
                {
                    b.HasOne("Demo.Shared.Domain.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_votes_posts_post_id");

                    b.HasOne("Demo.Shared.Domain.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_votes_users_user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("post_tags", b =>
                {
                    b.HasOne("Demo.Shared.Domain.Post", null)
                        .WithMany()
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tags_posts_post_id");

                    b.HasOne("Demo.Shared.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_tags_tags_tag_id");
                });

            modelBuilder.Entity("user_badges", b =>
                {
                    b.HasOne("Demo.Shared.Domain.Badge", null)
                        .WithMany()
                        .HasForeignKey("badge_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_badges_badges_badge_id");

                    b.HasOne("Demo.Shared.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_badges_users_user_id");
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("Demo.Shared.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Demo.Shared.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Demo.Shared.Domain.Post", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("ChildAnswers");

                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Demo.Shared.Domain.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostApprovals");

                    b.Navigation("Posts");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
